name: 'OrangePay Process Designer Generator'
description: 'Generates Kotlin code from process.json and XML schemas'

runs:
  using: 'composite'
  steps:
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Generator
      shell: bash
      run: java -jar "${{ github.action_path }}/generator-all.jar"
